name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          NODE_ENV: production
          SKIP_OPTIMIZE_IMAGES: true
      - run: yarn lint
      - run: npx -p @percy/cli percy snapshot ./public
        if: github.actor == 'jakejarvis'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
