name: Release

on: deployment_status

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: |
          LOWERENV=$(echo "${{ github.event.deployment_status.environment }}" | tr "[:upper:]" "[:lower:]")
          echo "NORMALIZED_ENV=${LOWERENV}" >> $GITHUB_ENV
      - uses: getsentry/action-release@v1
        if: ${{ env.NORMALIZED_ENV == 'production' }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: jakejarvis
          SENTRY_PROJECT: jarvis
        with:
          environment: ${{ env.NORMALIZED_ENV }}
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install -g @lhci/cli
      - run: |
          chrome --version
          lhci --version
          curl https://lhci.jrvs.io/version || true
          echo "ref: ${{ github.event.deployment.ref }}"
          echo "env: ${{ env.NORMALIZED_ENV }}"
          echo "url: ${{ github.event.deployment_status.target_url }}"
      - if: ${{ env.NORMALIZED_ENV == 'production' }}
        run: |
          echo "BASE_DEPLOY_URL=https://jarv.is" >> $GITHUB_ENV
          echo "LHCI_EXTRA_FLAGS=" >> $GITHUB_ENV
          echo "LHCI_BUILD_CONTEXT__CURRENT_BRANCH=main" >> $GITHUB_ENV
      - if: ${{ env.NORMALIZED_ENV == 'preview' }}
        run: |
          echo "BASE_DEPLOY_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV
          echo "LHCI_EXTRA_FLAGS=--assert.assertions.is-crawlable=off --assert.assertions.canonical=off" >> $GITHUB_ENV
          echo "LHCI_BUILD_CONTEXT__CURRENT_BRANCH=${{ github.event.deployment.ref }}" >> $GITHUB_ENV
      - continue-on-error: true
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          lhci autorun ${{ env.LHCI_EXTRA_FLAGS }} \
            --collect.url=${{ env.BASE_DEPLOY_URL }}/ \
            --collect.url=${{ env.BASE_DEPLOY_URL }}/notes/how-to-pull-request-fork-github/ \
            --collect.url=${{ env.BASE_DEPLOY_URL }}/projects/ \
            --collect.url=${{ env.BASE_DEPLOY_URL }}/contact/
      - uses: actions/upload-artifact@v2
        with:
          name: lhci-results
          path: ./.lighthouseci
